# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('avatar', models.ImageField(upload_to='uploads/avatars')),
                ('bio', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(choices=[('website', 'Website'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('link', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Position'),
        ),
    ]
